:awestruct-layout: product-get-started
:awestruct-interpolate: true

## Path Intro section
Get started building Python applications in docker containers using the Red Hat Container Development CDK (CDK) 2.0

## Prerequisites section title
Introduction and Prerequisites

## Prerequisites section
In this tutorial, you will learn how to start building Python 3 applications in docker containers using the Red Hat Container Development Kit (CDK) 2.0 on Red Hat Enterprise Linux. You need to have CDK 2.0 installed and should have downloaded the rhel-cdk vagrant box for your system. See the CDK 2.0 Installation Guide for more information. [*FIXME -- Add link: CDK install guide(s)*]

If you encounter difficulties at any point, see <<troubleshooting,Troubleshooting and FAQ>>.

## Step1 Duration
5 minutes

## Step1 Title
Start the vagrant box

## Step2 Duration
5 minutes

## Step2 Title
Run your first container

## Step3 Duration
5 minutes

## Step3 Title
Build Hello World in a container

## Step1 Content
[*FIXME - Note to reviewers - leaving this section in temporarily*]

The steps in this tutorial run on the `rhel-cdk-kubernetes` vagrant box that you downloaded after installing the CDK. The vagrant box has docker and kubernetes installed and configur
ed for running containers. You will enter the commands in this tutorial after logging into the box with `vagrant ssh`.

Open a _Terminal_ or _command_ window to enter the commands in this tutorial.

If you haven't already installed the CDK, follow the _CDK Installation Guide_ for your operating system to:

. Install a virtualization provider (hypervisor) for your system such as VirtualBox, VMware, KVM/libvirt.
. Install vagrant, from link:http://vagrantup.com/[vagrantup.com], or from your operating system's packages.
. Download and unzip cdk-2.0.0.zip from [*FIXME point to access.redhat.com or developers.redhat.com?*]
. Install the vagrant plugins `vagrant-registration` and `vagrant-adbinfo`.  The plugins are located in the `plugins` directory of the CDK zip file.

If you haven't already downloaded and added the `rhel-cdk-kubernetes` box the steps are:

. Download the `rhel-cdk-kubernetes` box that matches your virtualization provider (VirtualBox, VMware, or KVM/libvirt).  Note the filename/path of the saved `.box` file.
. Add the vagrant box with the command `vagrant add --name cdkv2 _path to saved .box file_`.

### Start the vagrant box

To start the vagrant box:

. Change to the directory where you unpacked the CDK zip file.
. Change to the sub-direcotry `components/rhel/rhel-ose`. Alternatively, copy the `Vagrantfile` in that directory to a working directory of your choosing.
. Start the box by entering `vagrant up`. Note: the `Vagrantfile` needs to be in the current directory when entering vagrant commands without specifying a box name or a path to the `Vagrantfile`.

You should now be able to log into the vagrant box using `vagrant ssh`.

## Step2 Content

This step will download and install Python 3 using a container from the Red Hat container registry. Installing the Python 3 container will make Python 3 available for use by other containers on your system. Because containers run in isolated environments, your host system will not be altered by the installation. You must use `docker` commands to use or view the container's content.

The commands shown in this section can be used to download and install other containers, like application containers you build. Containers can specify that they require other containers to be installed, which can happen automatically. For example, you can specify in the `Dockerfile` that is used to describe and build your container that your application requires Python 3. Then, when someone installs your container, their system will automatically download the required Python 3 container directly from the Red Hat container registry.

The Python 3 container is part of Red Hat Software Collections, which provides the latest development technologies for Red Hat Enterprise Linux. Access to the Red Hat Software Collections (RHSCL) is included with many Red Hat Enterprise Linux (RHEL) subscriptions. For more information about which subscriptions include RHSCL, see link:https://access.redhat.com/solutions/472793[How to use Red Hat Software Collections (RHSCL) or Red Hat Developer Toolset (DTS)].

All of the following commands are run on the vagrant box. If you haven't logged into the vagrant box, open a _Terminal_ or _command_ window and change to the direotory with the `rhel-ose/Vagrantfile`.  Log in with `vagrant ssh`


To download and install the Python 3 container, use the following command:

`$ docker pull registry.access.redhat.com/rhscl/python-34-rhel7`

The `docker images` command shows the container image that was installed as well as any others that are on your system.

`$ docker images`

Now start a `bash` shell inside the Python 3 container to have a look around. The shell prompt changes, which is an indication that you are typing at the shell inside the container. A `ps -ef` shows the only thing running inside the container is `bash` and `ps`. Type `exit` to leave the container's bash shell.

[.code-block]
```
$ docker run -it rhscl/python-34-rhel7 /bin/bash
bash-4.2$ which python3
/opt/rh/rh-python34/root/usr/bin/python3
bash-4.2$ python3 --version
Python 3.4.2
bash-4.2$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
default      1     0  0 17:58 ?        00:00:00 /bin/bash
default     10     1  0 17:58 ?        00:00:00 ps -ef
bash-4.2$ exit
```

The prior `docker run` command created a container to run your command, keep any state, and isolate it from the rest of the system. You can view the list of running containers with `docker ps`. To see all of the containers that have been created, including those that have exited, use `docker ps -a`. Depending on which Vagrantfile you used there may be a number of other containers running such as containers used to create an OpenShift environment.

You can restart the container that was created above with `docker start`. Containers are referred to by name. Docker will automatically generate a name if you don't provide one. Once the container has been restarted, `docker attach` will let you interact with the shell running inside of it.  See the following example:
 
[.code-block]
```
$ docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS                          PORTS               NAMES
d949277c36e9        rhscl/python-34-rhel7        "container-entrypoint"   About a minute ago   Exited (0) About a minute ago                       determined_mayer

$ docker start determined_mayer
determined_mayer
$ docker attach determined_mayer
```

At this point you are connected to the running shell inside the container. When you attach you won't see the command prompt, so hit Enter to get it to print another one.

[.code-block]
```
bash-4.2$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
default      1     0  0 18:01 ?        00:00:00 /bin/bash
default      9     1  0 18:01 ?        00:00:00 ps -ef
bash-4.2$ exit
```

Since the only process in the container, `bash`, was told to `exit` the container will no longer be running. This can be verified with `docker ps -a`. Containers that are no longer needed can be cleaned up with `docker rm _<container-name>_`.

`$ docker rm determined_mayer`

To see what other containers are available in the Red Hat container registry, use one or more of the following searches:

[.code-block]
```
$ docker search registry.access.redhat.com/rhscl
$ docker search registry.access.redhat.com/openshift3
$ docker search registry.access.redhat.com/rhel
$ docker search registry.access.redhat.com/jboss
```

If you need help, see <<troubleshooting,Troubleshooting and FAQ>>.


## Step3 Content

In this step, you will create a tiny Hello World container that uses Python 3 as a web server. Once created, the container can be run on other systems that have `docker` installed.  You will need to create several files in an empty directory using your favorite editor, including a `Dockerfile` that describes the container.

Note: you can edit files on your host system that can be synchronized to your vagrant box with `vagrant sync`. For more information see _Vagrant synchronizad folders_ in the _CDK Installation Guide_. 

First, create an empty directory, and then create a file named `index.html` with the following contents:

.index.html
----
<html>Hello, Red Hat Developers World!</html>
----

Now in the same directory, create a file named `Dockerfile` with the following contents, but change the `MAINTAINER` line to have your name and email address:

.Dockerfile
----
FROM rhscl/python-34-rhel7:latest

MAINTAINER Your Name "your-email@example.com"

EXPOSE 8000

COPY . /opt/app-root/src

CMD /bin/bash -c 'python3 -u web.py'
----

Create the file `web.py` with the following contents:

.web.py
----
#
# A very simple Python HTTP server
#

import http.server
import socketserver


PORT = 8000

Handler = http.server.SimpleHTTPRequestHandler

httpd = socketserver.TCPServer(("", PORT), Handler)

print("serving at port", PORT)
httpd.serve_forever()
----


Now build the container image using `docker build`. You will need to be root using `su` or `sudo` in the directory you created that contains `Dockerfile` and `index.html`.

`$ docker build -t _myname_/pythonweb .`


You can see the container image that was created using the following command:

[.code-block]
```
$ docker images
```

Now run the container using `docker run`. The Python 3 http.server module will create a tiny web server that listens on port 8000 inside the container.  The `run` command will map port 8000 on the host machine to port 8000 inside the container.

`$ docker run -d -p 8000:8000 _myname_/pythonweb`

The run command returns an ID for the container that you can ignore.  To check that the container is running, use `docker ps`.  Take note of the name that docker assigned to the running container.

[.code-block]
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
c7885aa23773        myname/pythonweb    "container-entrypoint"   6 seconds ago       Up 4 seconds        0.0.0.0:8000->8000/tcp, 8080/tcp   grave_brown
```

Use `curl` to access the Python web server:

[.code-block]
```
# curl http://localhost:8000/
<html>Hello, Red Hat Developers World!</html>
```

Note: you should also be able to access the Python web server running inside your container from the browser on your host machine. The `rhel-ose/Vagrantfile` sets the vagrant box's IP address to 10.1.2.2. The url to use is `http://10.1.2.2/`.

To view the logs from the running container use `docker logs _<container-name>_`:

`$ docker logs grave_brown`

When you are done, stop the running container with the following command using the name obtained from running `docker ps`:

[.code-block]
```
$ docker kill grave_brown
```

Information about a container is available using `docker inspect`:

`$ docker inspect _myname_/pythonweb`

The output is a JSON structure that is easily readable. The _Config_ section has details of the container's runtime environment such as environment variables and default command. Note that much of the information in the container's configuration was inherited from the parent container, which in this case is the Python 3 runtime container.


## Where to go next?

* link:https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/getting-started-with-containers/[Red Hat Enterprise Linux Atomic Host 7 Getting Started with Containers] -- This document covers working with and deploying containers on both Red Hat Enterprise Linux and Red Hat Enterprise Linux Atomic Host. It also provides information on orchestrating multi-container environments with _kubernetes_. See <<About Red Hat Enterprise Linux Atomic Host>>. 

* link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/[Red Hat Enterprise Linux 7.2 Release Notes] -- includes information on recent updates to the link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/atomic_host_and_containers.html[container tools included in Red Hat Enterprise Linux and Atomic Host].


## More Resources

### Become a Red Hat developer: developers.redhat.com

Red Hat delivers the resources and ecosystem of experts to help you be more productive and build great solutions.  Register for free at link:http://developers.redhat.com/[developers.redhat.com].

*Follow the Red Hat Developer Blog* +
link:http://developerblog.redhat.com/[]



## Faq section title
[[troubleshooting]]Troubleshooting and FAQ

## Faq section

. How do I tell if there is a container image available that has a newer version of Python 3?
+
How can I see what other container images are available?
+
I can't find the container mentioned in this tutorial, how can I tell if the name changed?
+
To see what other containers are available in the Red Hat container registry, use one or more of the following searches:
+
[.code-block]
```
$ docker search registry.access.redhat.com/rhscl
$ docker search registry.access.redhat.com/openshift3
$ docker search registry.access.redhat.com/rhel
$ docker search registry.access.redhat.com/jboss
```
+
. Where can I learn more about delivering applications with Linux containers?
+
If you haven't already joined the link:http://developers.redhat.com/[Red Hat Developers program], sign up at link:http://developers.redhat.com/[developers.redhat.com]. Membership is free. +
link:https://access.redhat.com/articles/1483053[Recommended Practices for Container Development] and many other container articles are available from the link:https://access.redhat.com/[Red Hat Customer Portal]. +
If you are a Red Hat Technology Partner, visit the link:https://access.redhat.com/articles/1483053[Container Zone] at the link:http://connect.redhat.com/[Red Hat Connect for Technology Partners] web site.
